#!/bin/bash

# Array com mapeamento de cidades para estados
declare -A city_states=(
    ["aguas-de-lindoia"]="sp"
    ["alpinopolis"]="mg"
    ["aracaju"]="se"
    ["araras"]="sp"
    ["araraquara"]="sp"
    ["ararangua"]="sc"
    ["aral-moreira"]="ms"
    ["arceburgo"]="mg"
    ["assis"]="sp"
    ["atibaia"]="sp"
    ["barueri"]="sp"
    ["betim"]="mg"
    ["birigui"]="sp"
    ["blumenau"]="sc"
    ["botucatu"]="sp"
    ["braganca-paulista"]="sp"
    ["brusque"]="sc"
    ["bento-goncalves"]="rs"
    ["belo-horizonte"]="mg"
    ["bauru"]="sp"
    ["campinas"]="sp"
    ["caconde"]="sp"
    ["caieiras"]="sp"
    ["cambuquira"]="mg"
    ["caratinga"]="mg"
    ["caxambu"]="mg"
    ["chapeco"]="sc"
    ["conselheiro-lafaiete"]="mg"
    ["contagem"]="mg"
    ["curitiba"]="pr"
    ["criciuma"]="sc"
    ["dourados"]="ms"
    ["estiva-gerbi"]="sp"
    ["faria-lemos"]="mg"
    ["farroupilha"]="rs"
    ["franco-da-rocha"]="sp"
    ["francisco-morato"]="sp"
    ["gaviao-peixoto"]="sp"
    ["goiania"]="go"
    ["governador-valadares"]="mg"
    ["guaranesia"]="mg"
    ["guaxupe"]="mg"
    ["ilha-comprida"]="sp"
    ["indaiatuba"]="sp"
    ["ipatinga"]="mg"
    ["itajuba"]="mg"
    ["itamogi"]="mg"
    ["itapira"]="sp"
    ["itatiba"]="sp"
    ["itu"]="sp"
    ["jaragua-do-sul"]="sc"
    ["joanopolis"]="sp"
    ["joao-pessoa"]="pb"
    ["jundiai"]="sp"
    ["laguna"]="sc"
    ["lajeado"]="rs"
    ["limeira"]="sp"
    ["londrina"]="pr"
    ["marilia"]="sp"
    ["maringa"]="pr"
    ["mogi-guacu"]="sp"
    ["monte-alegre-do-sul"]="sp"
    ["monte-belo"]="mg"
    ["muzambinho"]="mg"
    ["natal"]="rn"
    ["nova-resende"]="mg"
    ["nova-rodelas"]="ba"
    ["novo-hamburgo"]="rs"
    ["olinda"]="pe"
    ["ourinhos"]="sp"
    ["pato-branco"]="pr"
    ["patos-de-minas"]="mg"
    ["ponta-pora"]="ms"
    ["porto-uniao"]="sc"
    ["pouso-alegre"]="mg"
    ["presidente-prudente"]="sp"
    ["pratapolis"]="mg"
    ["quatro-barras"]="pr"
    ["recife"]="pe"
    ["rio-grande"]="rs"
    ["salvador"]="ba"
    ["santana-do-parnaiba"]="sp"
    ["santa-cruz-do-sul"]="rs"
    ["santo-andre"]="sp"
    ["sao-carlos"]="sp"
    ["sao-jose-dos-campos"]="sp"
    ["sao-lourenco"]="mg"
    ["sao-paulo"]="sp"
    ["sao-pedro-da-uniao"]="sc"
    ["serra-negra"]="sp"
    ["sete-lagoas"]="mg"
    ["soledade"]="rs"
    ["sorocaba"]="sp"
    ["tapiratiba"]="sp"
    ["teresopolis"]="rj"
    ["tombos"]="mg"
    ["tubarao"]="sc"
    ["uberaba"]="mg"
    ["uberlandia"]="mg"
    ["vacaria"]="rs"
    ["valinhos"]="sp"
    ["varginha"]="mg"
    ["vitoria"]="es"
)

# Encontrar todas as imagens fora da pasta cities
find public/images -name "*.jpg" -not -path "public/images/cities/*" | while read image; do
    # Extrair nome do arquivo sem extensão
    filename=$(basename "$image" .jpg)
    
    # Obter estado correspondente
    state="${city_states[$filename]}"
    
    if [[ -n "$state" ]]; then
        # Extrair primeira letra do nome da cidade (converter para minúscula)
        first_letter=${filename:0:1}
        
        # Criar diretório de destino se não existir
        dest_dir="public/images/cities/$state/$first_letter"
        mkdir -p "$dest_dir"
        
        # Mover imagem
        echo "Movendo $filename.jpg para $dest_dir/"
        mv "$image" "$dest_dir/$filename.jpg"
    else
        echo "Estado não encontrado para: $filename"
    fi
done

echo "Movimentação concluída!"